services:
  app:
    build: .
    volumes:
      - /app/node_modules/
      - .:/app
    ports:
      - "${PORT}:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    command: npm run dev